check tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -91,10 +91,10 @@ jobs:
           env:
             VAR: 3
           run: |
-            timeout 10 ./usr/bin/tests || true
-            echo "Exit code: $?"
-            timeout 10  ./usr/bin/isPrime "$VAR1" || true
-            echo "Exit code: $?"
+            timeout 30 ./usr/bin/tests || true
+            #echo "Exit code: $?"
+            timeout 30  ./usr/bin/isPrime "$VAR1" || true
+            #echo "Exit code: $?"
            
 
         - name: Save test result artifact
